# Use the official Node.js image as the base image
FROM node:18 AS build

# Define build argument for hostname
ARG HOME_HOSTNAME

ENV EXPO_PUBLIC_HOME_BASE_URL=http://${HOME_HOSTNAME}:8000
ENV EXPO_PUBLIC_LOCAL_BASE_URL=http://${HOME_HOSTNAME}:8080

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 80

CMD ["npx", "expo", "start", "--web", "--port", "80"]
