# Use the official Node.js image as the base image
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 80

CMD ["npx", "expo", "start", "--web", "--port", "80"]
