# Generated by Django 4.2 on 2024-09-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_type', models.CharField(choices=[('computer', 'Computer'), ('phone', 'Phone'), ('tv', 'TV')], max_length=20)),
                ('status_updated_at', models.DateTimeField(null=True)),
                ('cpu_usage', models.FloatField(null=True)),
                ('cpu_temp', models.FloatField(null=True)),
                ('mem_usage', models.FloatField(null=True)),
                ('disk_usage', models.FloatField(null=True)),
                ('network_sent', models.BigIntegerField(null=True)),
                ('network_received', models.BigIntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='core.location')),
            ],
        ),
    ]
