# Generated by Django 5.0.6 on 2024-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system_type', models.CharField(choices=[('computer', 'Computer'), ('phone', 'Phone'), ('tv', 'TV')], max_length=20)),
            ],
        ),
    ]
