# Generated by Django 4.2 on 2024-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='cpu_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='cpu_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='disk_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='mem_usage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='network_received',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='network_sent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='status_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
