services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./services/db/.env
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "0"

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "1"

  home:
    build: ./services/home
    volumes:
      - ./services/home:/code
    ports:
      - "8000:8000"
    env_file:
      - ./services/home/.env
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://home:8000/api/"]
      interval: 5s
      timeout: 2s
      retries: 40
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.33"
    cpuset: "2"

  mqtt-broker:
    build: ./services/mqtt-broker
    ports:
      - "1883:1883"
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "3"

  controller:
    build: ./services/controller
    volumes:
      - ./services/controller:/code
    depends_on:
      home:
        condition: service_healthy
      mqtt-broker:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "0"

  system-reporter:
    build: ./services/system-reporter
    volumes:
      - ./services/system-reporter:/app
    env_file:
      - ./services/system-reporter/.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "1"
