services:
  db:
    image: "postgres"
    hostname: home-db
    ports:
      - "5432:5432"
    env_file:
      - ./services/db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Mount volume for DB data persistence
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "0"
    networks:
      - home_network
    restart: unless-stopped

  redis:
    image: "redis:7"
    hostname: home-redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "1"
    networks:
      - home_network
    restart: unless-stopped

  api:
    build: ./services/home
    hostname: home-api
    volumes:
      - ./services/home:/code
    ports:
      - "8000:8000"
    env_file:
      - ./services/home/.env
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.5"
    cpuset: "2"
    networks:
      - home_network
    restart: unless-stopped

  mqtt-broker:
    hostname: home-mqtt-broker
    build: ./services/mqtt-broker
    ports:
      - "1883:1883"
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "3"
    networks:
      - home_network
    restart: unless-stopped

  controller:
    hostname: home-controller
    build: ./services/controller
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./services/controller:/code
    env_file:
      - ./services/controller/.env
      - ./services/controller/.env.${HOME_ENV:-production}
    depends_on:
      mqtt-broker:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "0"
    networks:
      - home_network
    restart: unless-stopped

  system-reporter:
    build:
      context: ./services/system-reporter
      dockerfile: Dockerfile.${HOME_ENV:-production}
    volumes:
      - ./services/system-reporter:/app
    env_file:
      - ./services/system-reporter/.env.${HOME_ENV:-production}
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "1"
    networks:
      - home_network
    restart: unless-stopped
    profiles:
      - optional

  client:
    hostname: home-client
    image: home-client
    container_name: home-client
    build:
      context: ./client
      dockerfile: Dockerfile.${HOME_ENV:-production}
    volumes:
      - ./client:/app
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "2"
    networks:
      - home_network
    ports:
      - "3002:80"
    expose:
      - "80"
    restart: unless-stopped

  avahi:
    build: ./services/avahi
    network_mode: host # Required for Avahi to broadcast over the LAN
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
    cpuset: "3"

networks:
  home_network:
    driver: bridge

volumes:
  postgres_data: # Define the postgres_data volume
