# Generated by Django 4.2 on 2024-09-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status_updated_at', models.DateTimeField(null=True)),
                ('cpu_usage', models.FloatField(null=True)),
                ('cpu_temp', models.FloatField(null=True)),
                ('mem_usage', models.FloatField(null=True)),
                ('disk_usage', models.FloatField(null=True)),
                ('network_sent', models.BigIntegerField(null=True)),
                ('network_received', models.BigIntegerField(null=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.devicetype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.location')),
            ],
        ),
    ]
