# Generated by Django 4.2 on 2024-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
