# Generated by Django 4.2 on 2024-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cpu_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mem_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='network_received',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='network_sent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
