# Generated by Django 4.2 on 2024-09-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_environmental'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_status_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
