# Generated by Django 4.2 on 2024-10-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='brightness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light',
            name='color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light',
            name='is_on',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
