# Generated by Django 4.2 on 2024-10-16 05:52

from django.db import migrations


DEVICE_TYPES = [
    "Controller",
    "Dial",
    "Environmental",
    "Light",
    "PC",
    "Plug",
]


def create_device_types(apps, schema_editor):
    DeviceType = apps.get_model("devices", "DeviceType")
    for type_name in DEVICE_TYPES:
        DeviceType.objects.get_or_create(name=type_name)


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_alter_devicetype_name"),
    ]

    operations = [
        migrations.RunPython(create_device_types),
    ]
